In [13]:
import pandas as pd
import os

In [19]:
df = pd.read_csv("Características y composición del hogar.csv", sep= ";")
df

FileNotFoundError: [Errno 2] No such file or directory: 'Características y composición del hogar.csv'

In [7]:
df["DIRECTORIO"].duplicated().sum()

NameError: name 'df' is not defined

In [ ]:
datos_limpios = df.query("P6040 >= 18 and P753 == 2")
datos_limpios

,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P6016,P1894,P6020,P6034,P6040,...,P1898,P1899,P3175,P1901,P1903,P1904,P1905,P1927,P3038,P3039
4,8369551,1,1,1,"308,8543189",1,3,2,1,62,...,7.0,4.0,7.0,8.0,6.0,2.0,8.0,7.0,1.0,2.0
12,8369553,3,1,3,"268,976656",3,5,1,1,43,...,8.0,1.0,7.0,8.0,9.0,2.0,2.0,8.0,2.0,1.0
14,8369554,2,1,2,"353,9494419",2,3,1,1,64,...,8.0,5.0,9.0,7.0,3.0,3.0,8.0,6.0,2.0,1.0
32,8369561,1,1,1,"248,3358759",1,3,1,1,61,...,8.0,8.0,9.0,6.0,3.0,2.0,9.0,6.0,2.0,1.0
33,8369561,2,1,2,"248,3358759",2,3,2,1,61,...,8.0,6.0,10.0,7.0,3.0,3.0,10.0,8.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235296,8489492,1,1,1,"6,900677816",1,3,2,1,25,...,9.0,8.0,8.0,9.0,2.0,2.0,9.0,7.0,1.0,2.0
235298,8489493,1,1,1,"17,92111851",1,3,1,1,37,...,9.0,9.0,9.0,9.0,2.0,2.0,10.0,7.0,2.0,1.0
235319,8489505,2,1,2,"8,62584727",2,3,2,1,33,...,8.0,8.0,8.0,8.0,1.0,1.0,10.0,8.0,1.0,2.0
235321,8489507,1,1,1,"8,62584727",1,3,2,1,42,...,8.0,9.0,8.0,9.0,0.0,0.0,10.0,7.0,1.0,2.0
235322,8489507,2,1,2,"8,62584727",2,3,2,1,24,...,8.0,8.0,8.0,9.0,0.0,0.0,10.0,7.0,1.0,2.0

In [ ]:
datos_limpios = datos_limpios.drop(columns=["P3510S1","P3510S1A1","P3510S1A2","P3510S1A3",""])
datos_limpios

,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P6016,P1894,P6020,P6034,P6040,...,P1898,P1899,P3175,P1901,P1903,P1904,P1905,P1927,P3038,P3039
4,8369551,1,1,1,"308,8543189",1,3,2,1,62,...,7.0,4.0,7.0,8.0,6.0,2.0,8.0,7.0,1.0,2.0
12,8369553,3,1,3,"268,976656",3,5,1,1,43,...,8.0,1.0,7.0,8.0,9.0,2.0,2.0,8.0,2.0,1.0
14,8369554,2,1,2,"353,9494419",2,3,1,1,64,...,8.0,5.0,9.0,7.0,3.0,3.0,8.0,6.0,2.0,1.0
32,8369561,1,1,1,"248,3358759",1,3,1,1,61,...,8.0,8.0,9.0,6.0,3.0,2.0,9.0,6.0,2.0,1.0
33,8369561,2,1,2,"248,3358759",2,3,2,1,61,...,8.0,6.0,10.0,7.0,3.0,3.0,10.0,8.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235296,8489492,1,1,1,"6,900677816",1,3,2,1,25,...,9.0,8.0,8.0,9.0,2.0,2.0,9.0,7.0,1.0,2.0
235298,8489493,1,1,1,"17,92111851",1,3,1,1,37,...,9.0,9.0,9.0,9.0,2.0,2.0,10.0,7.0,2.0,1.0
235319,8489505,2,1,2,"8,62584727",2,3,2,1,33,...,8.0,8.0,8.0,8.0,1.0,1.0,10.0,8.0,1.0,2.0
235321,8489507,1,1,1,"8,62584727",1,3,2,1,42,...,8.0,9.0,8.0,9.0,0.0,0.0,10.0,7.0,1.0,2.0
235322,8489507,2,1,2,"8,62584727",2,3,2,1,24,...,8.0,8.0,8.0,9.0,0.0,0.0,10.0,7.0,1.0,2.0

In [ ]:
datos_limpios.nunique().reset_index()

                 index      0
0           DIRECTORIO  26164
1   SECUENCIA_ENCUESTA     11
2          SECUENCIA_P      3
3                ORDEN     11
4                FEX_C  20920
..                 ...    ...
69               P1904     11
70               P1905     11
71               P1927     11
72               P3038      5
73               P3039      6

[74 rows x 2 columns]

In [ ]:
datos_limpios.isnull().sum().reset_index()

                 index  0
0           DIRECTORIO  0
1   SECUENCIA_ENCUESTA  0
2          SECUENCIA_P  0
3                ORDEN  0
4                FEX_C  0
..                 ... ..
69               P1904  0
70               P1905  0
71               P1927  0
72               P3038  0
73               P3039  0

[74 rows x 2 columns]

In [6]:
nombre_archivo = "datos_limpios1.csv"
ruta_salida = os.path.join(os.getcwd(), nombre_archivo)
datos_limpios.to_csv(ruta_salida, index = False, encoding= "utf-8-sig")

NameError: name 'datos_limpios' is not defined

# Bienestar y caracteristicas de la poblacion

## pregunta analitica

In [ ]:
grupo = datos_limpios.groupby("P6020")[["P1927","P1899","P3175","P1898","P1897","P1896"]].mean().reset_index()
grupo

   P6020     P1927     P1899     P3175     P1898
0      1  7.688387  7.606331  7.609979  7.807431
1      2  7.694972  7.320628  7.638918  7.754031

In [ ]:
grupo1 = datos_limpios.groupby("P756")[["P1927","P1899","P3175","P1898","P1897","P1896"]].mean().reset_index()
grupo1

   P756     P1927     P1899     P3175     P1898     P1897      P1896
0     1  7.601187  7.385630  7.534608  7.798286  7.786421  16.821028
1     2  7.713344  7.457448  7.634119  7.769538  7.828818  20.112421
2     3  7.614640  7.457955  7.628554  7.822545  8.181488  17.779593