In [374]:
import pandas as pd
import os

In [375]:
df = pd.read_csv("../Data/Raw/Características y composición del hogar.csv", sep= ";")
df

,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P6016,P1894,P6020,P6034,P6040,...,P1898,P1899,P3175,P1901,P1903,P1904,P1905,P1927,P3038,P3039
0,8369550,1,1,1,"472,1319014",1,3,2,1,45,...,10.0,5.0,7.0,10.0,6.0,0.0,7.0,6.0,1.0,2.0
1,8369550,2,1,2,"472,1319014",2,3,1,1,25,...,10.0,8.0,7.0,10.0,0.0,0.0,8.0,8.0,2.0,1.0
2,8369550,3,1,3,"472,1319014",3,2,2,1,16,...,10.0,10.0,10.0,10.0,0.0,0.0,10.0,10.0,NaN,NaN
3,8369550,4,1,4,"472,1319014",4,2,1,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8369551,1,1,1,"308,8543189",1,3,2,1,62,...,7.0,4.0,7.0,8.0,6.0,2.0,8.0,7.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235345,8489520,2,1,2,"19,04352805",2,3,2,1,31,...,10.0,10.0,10.0,10.0,1.0,0.0,9.0,9.0,1.0,2.0
235346,8489520,3,1,3,"19,04352805",3,1,2,1,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235347,8489521,1,1,1,"19,04352805",1,3,1,1,31,...,10.0,9.0,9.0,10.0,1.0,0.0,10.0,9.0,2.0,1.0
235348,8489521,2,1,2,"19,04352805",2,3,2,1,32,...,10.0,10.0,9.0,9.0,1.0,1.0,10.0,9.0,1.0,2.0
235349,8489522,1,1,1,"10,35101672",1,3,1,1,45,...,8.0,8.0,8.0,8.0,1.0,0.0,10.0,6.0,2.0,1.0

In [376]:
df["DIRECTORIO"].duplicated().sum()

np.int64(148502)

In [377]:
datos_limpios = df.query("P6040 >= 18")
datos_limpios

,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P6016,P1894,P6020,P6034,P6040,...,P1898,P1899,P3175,P1901,P1903,P1904,P1905,P1927,P3038,P3039
0,8369550,1,1,1,"472,1319014",1,3,2,1,45,...,10.0,5.0,7.0,10.0,6.0,0.0,7.0,6.0,1.0,2.0
1,8369550,2,1,2,"472,1319014",2,3,1,1,25,...,10.0,8.0,7.0,10.0,0.0,0.0,8.0,8.0,2.0,1.0
4,8369551,1,1,1,"308,8543189",1,3,2,1,62,...,7.0,4.0,7.0,8.0,6.0,2.0,8.0,7.0,1.0,2.0
5,8369552,1,1,1,"428,5162391",1,3,2,1,38,...,5.0,8.0,8.0,8.0,2.0,2.0,8.0,8.0,1.0,2.0
6,8369552,2,1,2,"428,5162391",2,3,1,1,49,...,5.0,8.0,8.0,8.0,2.0,3.0,8.0,8.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235344,8489520,1,1,1,"19,04352805",1,3,1,1,32,...,10.0,10.0,9.0,9.0,0.0,1.0,9.0,9.0,2.0,1.0
235345,8489520,2,1,2,"19,04352805",2,3,2,1,31,...,10.0,10.0,10.0,10.0,1.0,0.0,9.0,9.0,1.0,2.0
235347,8489521,1,1,1,"19,04352805",1,3,1,1,31,...,10.0,9.0,9.0,10.0,1.0,0.0,10.0,9.0,2.0,1.0
235348,8489521,2,1,2,"19,04352805",2,3,2,1,32,...,10.0,10.0,9.0,9.0,1.0,1.0,10.0,9.0,1.0,2.0
235349,8489522,1,1,1,"10,35101672",1,3,1,1,45,...,8.0,8.0,8.0,8.0,1.0,0.0,10.0,6.0,2.0,1.0

In [378]:
datos_limpios = datos_limpios.drop(columns=["P3510S1","P3510S1A1","P3510S1A2","P3510S1A3"])
datos_limpios

,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P6016,P1894,P6020,P6034,P6040,...,P1898,P1899,P3175,P1901,P1903,P1904,P1905,P1927,P3038,P3039
0,8369550,1,1,1,"472,1319014",1,3,2,1,45,...,10.0,5.0,7.0,10.0,6.0,0.0,7.0,6.0,1.0,2.0
1,8369550,2,1,2,"472,1319014",2,3,1,1,25,...,10.0,8.0,7.0,10.0,0.0,0.0,8.0,8.0,2.0,1.0
4,8369551,1,1,1,"308,8543189",1,3,2,1,62,...,7.0,4.0,7.0,8.0,6.0,2.0,8.0,7.0,1.0,2.0
5,8369552,1,1,1,"428,5162391",1,3,2,1,38,...,5.0,8.0,8.0,8.0,2.0,2.0,8.0,8.0,1.0,2.0
6,8369552,2,1,2,"428,5162391",2,3,1,1,49,...,5.0,8.0,8.0,8.0,2.0,3.0,8.0,8.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235344,8489520,1,1,1,"19,04352805",1,3,1,1,32,...,10.0,10.0,9.0,9.0,0.0,1.0,9.0,9.0,2.0,1.0
235345,8489520,2,1,2,"19,04352805",2,3,2,1,31,...,10.0,10.0,10.0,10.0,1.0,0.0,9.0,9.0,1.0,2.0
235347,8489521,1,1,1,"19,04352805",1,3,1,1,31,...,10.0,9.0,9.0,10.0,1.0,0.0,10.0,9.0,2.0,1.0
235348,8489521,2,1,2,"19,04352805",2,3,2,1,32,...,10.0,10.0,9.0,9.0,1.0,1.0,10.0,9.0,1.0,2.0
235349,8489522,1,1,1,"10,35101672",1,3,1,1,45,...,8.0,8.0,8.0,8.0,1.0,0.0,10.0,6.0,2.0,1.0

In [379]:
datos_limpios.nunique().reset_index()

                 index      0
0           DIRECTORIO  86759
1   SECUENCIA_ENCUESTA     16
2          SECUENCIA_P      6
3                ORDEN     16
4                FEX_C  57166
..                 ...    ...
69               P1904     11
70               P1905     11
71               P1927     11
72               P3038      5
73               P3039      6

[74 rows x 2 columns]

In [380]:
datos_limpios.isnull().sum().reset_index()

                 index  0
0           DIRECTORIO  0
1   SECUENCIA_ENCUESTA  0
2          SECUENCIA_P  0
3                ORDEN  0
4                FEX_C  0
..                 ... ..
69               P1904  0
70               P1905  0
71               P1927  0
72               P3038  0
73               P3039  0

[74 rows x 2 columns]

In [381]:
nombre_archivo = "datos_limpios1.csv"
ruta_salida = os.path.join(os.getcwd(), nombre_archivo)
datos_limpios.to_csv(ruta_salida, index = False, encoding= "utf-8-sig")

# Bienestar y caracteristicas de la poblacion

## pregunta analitica

¿Cómo varía el bienestar (este es medido como el promedio de satisfacción con la vida, salud, ingreso, seguridad, trabajo y tiempo libre) según el sexo y el estado civil de las personas?

# DIC variables
#### P6020 = Sexo al nacer  (NOMINAL)
#### P6040 = Años Cumplidos (NUMERICA-discreta)
#### P1927 = Escalon de vida de 0-10 (ordinal)
#### P1899 = Satisfaciion con el trabajo actual 0-10 (ordinal)
#### P3175 = Satisfaccion con el tiempo libre 0-10(ordinal)
#### P1898 = Satisfaccion con la seguridad 0-10(ordinal)
#### P1897 = Satisfaccion con la salud 0-10(ordinal)
#### P1896 = Satisfaccion con el ingreso 0-10(ordinal)
#### P1895 = Satisfaciion con su vida en general 0-10 (ordinal)
#### P1905 = Consideracion de que las cosas que en su vida valen la pena 0-10 (ordinal)
#### P6074 = siempre ha vivido en el municipio(NOMINAL)
#### P5502 = Estado civil (NOMINAL)

In [382]:
variables = ["P1927","P1899","P3175","P1898","P1897","P1896", "P1901", "P1903","P1895","P1904", "P1905"]
datos_limpios[variables].corr()

,P1927,P1899,P3175,P1898,P1897,P1896,P1901,P1903,P1895,P1904,P1905
P1927,1.000000,0.450947,0.441145,0.382159,0.447282,-0.001824,0.489045,-0.313738,0.543273,-0.313500,0.498693
P1899,0.450947,1.000000,0.498272,0.416041,0.477189,-0.080358,0.426817,-0.285065,0.498499,-0.271127,0.394095
P3175,0.441145,0.498272,1.000000,0.453208,0.438546,0.064495,0.450248,-0.295727,0.491595,-0.281930,0.409499
P1898,0.382159,0.416041,0.453208,1.000000,0.444097,0.040834,0.376102,-0.268435,0.440762,-0.264714,0.356627
P1897,0.447282,0.477189,0.438546,0.444097,1.000000,-0.013700,0.479291,-0.314262,0.559077,-0.350309,0.451255
P1896,-0.001824,-0.080358,0.064495,0.040834,-0.013700,1.000000,0.012226,-0.045586,0.020343,-0.042102,0.021759
P1901,0.489045,0.426817,0.450248,0.376102,0.479291,0.012226,1.000000,-0.465857,0.536049,-0.479244,0.475281
P1903,-0.313738,-0.285065,-0.295727,-0.268435,-0.314262,-0.045586,-0.465857,1.000000,-0.337279,0.675048,-0.313207
P1895,0.543273,0.498499,0.491595,0.440762,0.559077,0.020343,0.536049,-0.337279,1.000000,-0.363352,0.530877
P1904,-0.313500,-0.271127,-0.281930,-0.264714,-0.350309,-0.042102,-0.479244,0.675048,-0.363352,1.000000,-0.384478
P1905,0.498693,0.394095,0.409499,0.356627,0.451255,0.021759,0.475281,-0.313207,0.530877,-0.384478,1.000000

In [383]:
variables = ["P1927","P1899","P3175","P1898","P1897","P1896", "P1901", "P1895", "P1903", "P1904", "P1905"]
datos_limpios[variables].corr(method= "spearman")

,P1927,P1899,P3175,P1898,P1897,P1896,P1901,P1895,P1903,P1904,P1905
P1927,1.000000,0.504024,0.465848,0.413626,0.436662,0.349631,0.512581,0.534793,-0.339173,-0.325047,0.476135
P1899,0.504024,1.000000,0.593567,0.506936,0.529377,0.424453,0.510140,0.561664,-0.347587,-0.338908,0.456956
P3175,0.465848,0.593567,1.000000,0.521013,0.484896,0.381803,0.520593,0.537395,-0.349364,-0.338898,0.452959
P1898,0.413626,0.506936,0.521013,1.000000,0.509768,0.322767,0.455712,0.500508,-0.323745,-0.330941,0.415371
P1897,0.436662,0.529377,0.484896,0.509768,1.000000,0.316755,0.513875,0.565743,-0.347370,-0.379609,0.471558
P1896,0.349631,0.424453,0.381803,0.322767,0.316755,1.000000,0.325476,0.375746,-0.243118,-0.206508,0.250187
P1901,0.512581,0.510140,0.520593,0.455712,0.513875,0.325476,1.000000,0.579053,-0.517510,-0.518840,0.531443
P1895,0.534793,0.561664,0.537395,0.500508,0.565743,0.375746,0.579053,1.000000,-0.368854,-0.392201,0.546980
P1903,-0.339173,-0.347587,-0.349364,-0.323745,-0.347370,-0.243118,-0.517510,-0.368854,1.000000,0.697862,-0.359269
P1904,-0.325047,-0.338908,-0.338898,-0.330941,-0.379609,-0.206508,-0.518840,-0.392201,0.697862,1.000000,-0.441455
P1905,0.476135,0.456956,0.452959,0.415371,0.471558,0.250187,0.531443,0.546980,-0.359269,-0.441455,1.000000

In [384]:
var = ["P6020","P1927","P1899","P3175","P1898","P1897","P1896", "P1895", "P1901", "P1903", "P1904", "P5502", "P1905"]
usable = datos_limpios[var]
usable

,P6020,P1927,P1899,P3175,P1898,P1897,P1896,P1895,P1901,P1903,P1904,P5502,P1905
0,2,6.0,5.0,7.0,10.0,10.0,99.0,8.0,10.0,6.0,0.0,5.0,7.0
1,1,8.0,8.0,7.0,10.0,10.0,8.0,10.0,10.0,0.0,0.0,4.0,8.0
4,2,7.0,4.0,7.0,7.0,7.0,4.0,5.0,8.0,6.0,2.0,3.0,8.0
5,2,8.0,8.0,8.0,5.0,8.0,8.0,8.0,8.0,2.0,2.0,2.0,8.0
6,1,8.0,8.0,8.0,5.0,8.0,9.0,8.0,8.0,2.0,3.0,2.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
235344,1,9.0,10.0,9.0,10.0,9.0,9.0,9.0,9.0,0.0,1.0,2.0,9.0
235345,2,9.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,0.0,2.0,9.0
235347,1,9.0,9.0,9.0,10.0,10.0,10.0,10.0,10.0,1.0,0.0,2.0,10.0
235348,2,9.0,10.0,9.0,10.0,9.0,10.0,10.0,9.0,1.0,1.0,2.0,10.0
235349,1,6.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,1.0,0.0,4.0,10.0

In [385]:
usable["P1896"] = usable["P1896"].replace(99, pd.NA)
usable["P1896"] = pd.to_numeric(usable["P1896"], errors="coerce")

In [386]:
usable.dtypes

P6020      int64
P1927    float64
P1899    float64
P3175    float64
P1898    float64
P1897    float64
P1896    float64
P1895    float64
P1901    float64
P1903    float64
P1904    float64
P5502    float64
P1905    float64
dtype: object

In [387]:
usable.isnull().sum().reset_index()

    index      0
0   P6020      0
1   P1927      0
2   P1899      0
3   P3175      0
4   P1898      0
5   P1897      0
6   P1896  21681
7   P1895      0
8   P1901      0
9   P1903      0
10  P1904      0
11  P5502      0
12  P1905      0

In [388]:
usable.corr()

,P6020,P1927,P1899,P3175,P1898,P1897,P1896,P1895,P1901,P1903,P1904,P5502,P1905
P6020,1.000000,0.006200,-0.057114,0.011953,-0.011626,-0.032957,-0.087898,-0.003467,-0.015609,0.027186,0.034307,-0.031549,0.010175
P1927,0.006200,1.000000,0.450947,0.441145,0.382159,0.447282,0.442524,0.543273,0.489045,-0.313738,-0.313500,0.034364,0.498693
P1899,-0.057114,0.450947,1.000000,0.498272,0.416041,0.477189,0.599740,0.498499,0.426817,-0.285065,-0.271127,0.019832,0.394095
P3175,0.011953,0.441145,0.498272,1.000000,0.453208,0.438546,0.421589,0.491595,0.450248,-0.295727,-0.281930,0.033068,0.409499
P1898,-0.011626,0.382159,0.416041,0.453208,1.000000,0.444097,0.361065,0.440762,0.376102,-0.268435,-0.264714,0.022325,0.356627
P1897,-0.032957,0.447282,0.477189,0.438546,0.444097,1.000000,0.414482,0.559077,0.479291,-0.314262,-0.350309,-0.001462,0.451255
P1896,-0.087898,0.442524,0.599740,0.421589,0.361065,0.414482,1.000000,0.462464,0.388536,-0.252060,-0.204108,0.036581,0.294738
P1895,-0.003467,0.543273,0.498499,0.491595,0.440762,0.559077,0.462464,1.000000,0.536049,-0.337279,-0.363352,0.027783,0.530877
P1901,-0.015609,0.489045,0.426817,0.450248,0.376102,0.479291,0.388536,0.536049,1.000000,-0.465857,-0.479244,0.022501,0.475281
P1903,0.027186,-0.313738,-0.285065,-0.295727,-0.268435,-0.314262,-0.252060,-0.337279,-0.465857,1.000000,0.675048,-0.025164,-0.313207
P1904,0.034307,-0.313500,-0.271127,-0.281930,-0.264714,-0.350309,-0.204108,-0.363352,-0.479244,0.675048,1.000000,-0.020095,-0.384478
P5502,-0.031549,0.034364,0.019832,0.033068,0.022325,-0.001462,0.036581,0.027783,0.022501,-0.025164,-0.020095,1.000000,0.018798
P1905,0.010175,0.498693,0.394095,0.409499,0.356627,0.451255,0.294738,0.530877,0.475281,-0.313207,-0.384478,0.018798,1.000000

In [389]:
usable.describe().reset_index()

,index,P6020,P1927,P1899,P3175,P1898,P1897,P1896,P1895,P1901,P1903,P1904,P5502,P1905
0,count,172025.000000,172025.000000,172025.000000,172025.000000,172025.000000,172025.000000,150344.000000,172025.000000,172025.000000,172025.000000,172025.000000,172025.000000,172025.000000
1,mean,1.528882,7.655358,7.354739,7.585781,7.759564,7.839128,6.661343,8.142224,7.871995,2.617794,1.928987,3.877611,8.550513
2,std,0.499167,1.680805,2.201839,1.909613,1.948263,1.873769,2.363695,1.634644,1.956289,2.697198,2.459665,1.624904,1.620444
3,min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
4,25%,1.000000,7.000000,6.000000,7.000000,7.000000,7.000000,5.000000,7.000000,7.000000,0.000000,0.000000,2.000000,8.000000
5,50%,2.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,2.000000,1.000000,4.000000,9.000000
6,75%,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,4.000000,3.000000,5.000000,10.000000
7,max,2.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,6.000000,10.000000

In [390]:
usable.boxplot(column = "P6020")

In [391]:
variables_bienestar = ["P1895", "P1896", "P1897", "P1898", "P1899", "P3175"]
usable["bienestar"] = usable[variables_bienestar].mean(axis=1)
usable[["bienestar"] + variables_bienestar]

variables_emocionales = ["P1903", "P1904"]
usable["tristeza"] = usable[variables_emocionales].mean(axis=1)

variables_emocionales = ["P1901", "P1905"]
usable["felicidad"] = usable[variables_emocionales].mean(axis=1)

In [392]:
usable["bienestar"] = pd.to_numeric(usable["bienestar"], errors="coerce")
usable["tristeza"] = pd.to_numeric(usable["tristeza"], errors="coerce")
usable["felicidad"] = pd.to_numeric(usable["felicidad"], errors="coerce")
usable["P1896"].describe()

count    150344.000000
mean          6.661343
std           2.363695
min           0.000000
25%           5.000000
50%           7.000000
75%           8.000000
max          10.000000
Name: P1896, dtype: float64

In [393]:
usable[["P1895","P1896","P1897","P1898","P1899","P3175","bienestar"]].dtypes

P1895        float64
P1896        float64
P1897        float64
P1898        float64
P1899        float64
P3175        float64
bienestar    float64
dtype: object

In [394]:
usable["bienestar"].describe()

count    172025.000000
mean          7.576926
std           1.479549
min           0.000000
25%           6.666667
50%           7.666667
75%           8.600000
max          10.000000
Name: bienestar, dtype: float64

In [395]:
estado_civil = (
                usable.groupby("P5502")
                .agg(bienestar_promedio = ("bienestar", "mean"),
                tristeza_promedio=("tristeza", "mean"),
                felicidad_promedio = ("felicidad", "mean"),
                total_personas = ("bienestar", "count"))
)

genero = (
                usable.groupby("P6020")
                .agg(bienestar_promedio = ("bienestar", "mean"),
                tristeza_promedio=("tristeza", "mean"),
                felicidad_promedio = ("felicidad", "mean"),
                total_personas = ("bienestar", "count"))
)

estado_civil, genero

(       bienestar_promedio  tristeza_promedio  felicidad_promedio  \
 P5502
 1.0              7.740199           2.214599            8.348672
 2.0              7.569877           2.302529            8.207468
 3.0              7.229845           2.508408            7.928035
 4.0              7.478527           2.371446            8.146327
 5.0              7.608327           2.248930            8.208630
 6.0              7.698695           2.131093            8.331250

        total_personas
 P5502
 1.0              3651
 2.0             56869
 3.0             10644
 4.0             22337
 5.0             42767
 6.0             35757  ,
        bienestar_promedio  tristeza_promedio  felicidad_promedio  \
 P6020
 1                7.628125           2.189841            8.218696
 2                7.531319           2.347814            8.204625

        total_personas
 P6020
 1               81044
 2               90981  )